import {Food} from './app/shared/models/Food';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Chicken Burger',
    price: 4,
    cookTime: '40-50',
    favorite: true,
    origins: ['United States'],
    stars: 5.0,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Hamburger', 'Lauch'],
  },
  {
    id:'2',
    name: 'Cheese Sandwich',
    price: 2,
    cookTime: '30-35',
    favorite: true,
    origins: ['United States'],
    stars: 4.5,
    imageUrl: 'assets/food-2.jpg',
    tags: ['FastFood', 'Hamburger', 'Lauch'],
  },
  {
    id:'3',
    name: 'Cheese Burger',
    price: 3,
    cookTime: '20-30',
    favorite: false,
    origins: ['United States'],
    stars: 4.7,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger', 'Lauch'],
  },
  {
    id:'4',
    name: 'Spicy Chicken',
    price: 3,
    cookTime: '15-20',
    favorite: true,
    origins: ['American'],
    stars: 4.1,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Pizza', 'Lauch'],
  },
  {
    id:'5',
    name: 'Ice cream',
    price: 1,
    cookTime: '2-5',
    favorite: true,
    origins: ['Japan'],
    stars: 5.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['FastFood', 'Pizza', 'Lauch'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lauch'],
  },
]
